// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller.js"
application.register("address-autocomplete", AddressAutocompleteController)

import CanvasController from "./canvas_controller.js"
application.register("canvas", CanvasController)

import ClipboardController from "./clipboard_controller.js"
application.register("clipboard", ClipboardController)

import DescriptionController from "./description_controller.js"
application.register("description", DescriptionController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import ElevatorController from "./elevator_controller.js"
application.register("elevator", ElevatorController)

import GeolocationController from "./geolocation_controller.js"
application.register("geolocation", GeolocationController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import InputController from "./input_controller.js"
application.register("input", InputController)

import MapController from "./map_controller.js"
application.register("map", MapController)

import MappinsController from "./mappins_controller.js"
application.register("mappins", MappinsController)

import PlaceController from "./place_controller.js"
application.register("place", PlaceController)

